export const ADD_PET = 'ADD_PET'
export const REMOVE_PET = 'REMOVE_PET'
export const EDIT_PET = 'EDIT_PET'
export const SET_PETS = 'SET_PETS'
export const SET_TOYS = 'SET_TOYS'
export const ADD_TOY = 'ADD_TOY'
export const REMOVE_TOY = 'REMOVE_TOY'
export const EDIT_TOY = 'EDIT_TOY'